### PR TITLE
support debug output of sysfs writes

### PR DESCRIPTION
**Pull request by akostadinov**
It is very useful to know what actual writes the `rocm-smi` tool performs on
sysfs. In the future more debug output can be added for read operations as well
such that users can use the tool as an example for using the sysfs interface.

This is one of my very first times touching python code. Let me know if anything can be improved.

### CODE REVIEW

**Review by rigred — APPROVED** [review]
Looks good, I think this is a nice addition.

**Comment by kentrussell** [comment]
Never mind on the style stuff, it's not nearly important enough to worry about delaying this patch. I'm bringing it in internally now, Joseph and our tech lead can take a look, and we'll get it into 2.0.1/2.1. Thanks so much!

Edit: I did flesh out the commit message a bit. Mostly because our Gerrit server requires a Change-Id that I appended, and figured I could expand the commit message a little. Just for clarity and all that good stuff. In case someone else decides to look at the git log at some point :)

Edit2: I did remove one thing, I removed the \n from the string, otherwise it looks a little messy:
DEBUG:root:Writing to file /sys/class/drm/card0/device/power_dpm_force_performance_level:
high
GPU[0]          : Successfully set current Performance Level to high
DEBUG:root:Writing to file /sys/class/drm/card1/device/power_dpm_force_performance_level:
high
GPU[1]          : Successfully set current Performance Level to high

So keeping it on one line should help things to be a little more readable. I hope that's alright

**Comment by akostadinov** [comment]
I don't mind such changes, thank you. I have put value on separate line as I was not sure whether the tool will always write a single line or not.

**Comment by kentrussell** [comment]
We've pulled it internally, and it'll make it into the next release. Thanks again for all of your hard work! I'll close this once the next release is pushed out

**Comment by kentrussell** [comment]
Merged into 2.1

**Pull request closed without merging**
