### PR TITLE
make module python2 compatible

### PR DESCRIPTION
**Pull request by FooBarQuaxx**
* use environment python interpreter
* define print as function in python2

### CODE REVIEW

**Comment by kentrussell** [comment]
I'm pulling this into our master branch. If all goes well, we can add it to 1.8 and then push it out on the next release.

**Comment by FooBarQuaxx** [comment]
I think we may have to update the packaging metadata (RPM/rocm-smi.spec, DEBIAN/control) to require only python.

**Comment by kentrussell** [comment]
Indeed, I saw that too. Thanks for making sure that I didn't miss that though! I've got it in our internal testing and am aiming to get it into 1.8.1

**Comment by kentrussell** [comment]
This will be available in the next release after 1.8.1 (1.8.2 or 1.9, whichever is next) . I missed the cutoff window for 1.8.1.

**Pull request closed without merging**
